# Generated by Django 3.1.7 on 2021-05-24 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0003_auto_20210524_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('records', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='records.recording')),
            ],
        ),
    ]
