# Generated by Django 3.1.7 on 2021-05-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf',
        ),
    ]
