# Generated by Django 3.1.7 on 2021-05-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='email',
            new_name='user',
        ),
    ]
