# Generated by Django 3.1.7 on 2021-05-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20210524_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recording',
            name='typeScript',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
